# Generated by Django 5.2.8 on 2025-11-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, help_text='The word itself', max_length=100, unique=True)),
                ('is_noun', models.BooleanField(default=False, help_text='Whether word can be used as noun')),
                ('is_verb', models.BooleanField(default=False, help_text='Whether word can be used as verb')),
                ('embedding', models.JSONField(help_text='Store embedding vector as JSON array')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when word was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when word was last updated')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['word'],
                'indexes': [models.Index(fields=['word'], name='word_idx'), models.Index(fields=['is_noun'], name='noun_idx'), models.Index(fields=['is_verb'], name='verb_idx')],
            },
        ),
    ]
